// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjcijqsriihadhnhneoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqY2lqcXNyaWloYWRobmhuZW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzA1NzQsImV4cCI6MjA2OTA0NjU3NH0.ye0s8RIMdFRpFAbPpii3sFW9rytVJWf-PvyTQi3-juM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});